# Generated by Django 5.1.2 on 2025-11-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_license_type_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D'), ('E', 'Category E')], max_length=1),
        ),
    ]
