# Generated by Django 5.1.2 on 2025-11-07 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_alter_driver_license_type'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='drivers.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='trucks.truck')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'date'), name='unique_driver_per_day'), models.UniqueConstraint(fields=('truck', 'date'), name='unique_truck_per_day')],
            },
        ),
    ]
