# Generated by Django 5.1.2 on 2025-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('drivers', '0003_alter_driver_license_type'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_driver_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_truck_per_day',
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['driver', 'date'], name='assignments_driver__5be95f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['truck', 'date'], name='assignments_truck_i_af609d_idx'),
        ),
    ]
