# Generated by Django 5.1.2 on 2025-11-07 01:04

import trucks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7, unique=True, validators=[trucks.models.validate_plate])),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('minimum_license_type', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D'), ('E', 'Category E')], default='C', max_length=1)),
            ],
        ),
    ]
